/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.klinker.android.link_builder;

public final class R {
    public static final class attr {
        public static final int defaultLinkColor = 0x7f04008b;
        public static final int defaultTextColorOfHighlightedLink = 0x7f04008d;
        public static final int linkBuilderStyle = 0x7f040125;
    }
    public static final class styleable {
        public static final int[] LinkBuilder = { 0x7f04008b, 0x7f04008d };
        public static final int LinkBuilder_defaultLinkColor = 0;
        public static final int LinkBuilder_defaultTextColorOfHighlightedLink = 1;
    }
}
