/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package hollowsoft.slidingdrawer;

public final class R {
    public static final class attr {
        public static final int allowSingleTap = 0x7f040028;
        public static final int animateOnClick = 0x7f04002c;
        public static final int bottomOffset = 0x7f040046;
        public static final int content = 0x7f040074;
        public static final int handle = 0x7f0400c1;
        public static final int topOffset = 0x7f0401f2;
    }
    public static final class styleable {
        public static final int[] SlidingDrawer = { 0x010100c4, 0x7f040028, 0x7f04002c, 0x7f040046, 0x7f040074, 0x7f0400c1, 0x7f0401f2 };
        public static final int SlidingDrawer_android_orientation = 0;
        public static final int SlidingDrawer_allowSingleTap = 1;
        public static final int SlidingDrawer_animateOnClick = 2;
        public static final int SlidingDrawer_bottomOffset = 3;
        public static final int SlidingDrawer_content = 4;
        public static final int SlidingDrawer_handle = 5;
        public static final int SlidingDrawer_topOffset = 6;
    }
}
