/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * gradle plugin from the resource data it found. It
 * should not be modified by hand.
 */
package com.github.angads25.filepicker;

public final class R {
    public static final class anim {
        public static final int marked_item_animation = 0x7f010011;
        public static final int unmarked_item_animation = 0x7f010014;
    }
    public static final class attr {
        public static final int error_dir = 0x7f0400a1;
        public static final int extensions = 0x7f0400ab;
        public static final int offset_dir = 0x7f040166;
        public static final int root_dir = 0x7f040189;
        public static final int selection_mode = 0x7f040197;
        public static final int selection_type = 0x7f040198;
        public static final int title_text = 0x7f0401eb;
    }
    public static final class color {
        public static final int colorAccent = 0x7f06002d;
        public static final int colorHeader = 0x7f06002e;
        public static final int colorPrimary = 0x7f06002f;
        public static final int colorPrimaryDark = 0x7f060030;
        public static final int textColorPrimary = 0x7f060080;
        public static final int textColorSecondary = 0x7f060081;
    }
    public static final class dimen {
        public static final int activity_margin = 0x7f07004b;
        public static final int checkbox_dimens = 0x7f07004f;
        public static final int checkbox_margin = 0x7f070050;
        public static final int toolbar_image_margin = 0x7f0700c5;
    }
    public static final class drawable {
        public static final int bottom_shadow = 0x7f08005e;
    }
    public static final class id {
        public static final int cancel = 0x7f09002a;
        public static final int dir_path = 0x7f09005f;
        public static final int dir_select = 0x7f090060;
        public static final int dname = 0x7f090063;
        public static final int fileList = 0x7f090084;
        public static final int file_dir_select = 0x7f090085;
        public static final int file_mark = 0x7f090086;
        public static final int file_select = 0x7f090087;
        public static final int fname = 0x7f090090;
        public static final int footer = 0x7f090091;
        public static final int ftype = 0x7f090094;
        public static final int header = 0x7f090098;
        public static final int imageView = 0x7f0900a3;
        public static final int image_type = 0x7f0900a4;
        public static final int linearLayout = 0x7f0900b2;
        public static final int multi_mode = 0x7f0900d5;
        public static final int select = 0x7f09010b;
        public static final int single_mode = 0x7f090115;
        public static final int title = 0x7f09013d;
    }
    public static final class layout {
        public static final int dialog_file_list = 0x7f0b002f;
        public static final int dialog_file_list_item = 0x7f0b0030;
        public static final int dialog_footer = 0x7f0b0031;
        public static final int dialog_header = 0x7f0b0032;
        public static final int dialog_main = 0x7f0b0033;
    }
    public static final class mipmap {
        public static final int ic_directory_parent = 0x7f0d0000;
        public static final int ic_type_file = 0x7f0d0005;
        public static final int ic_type_folder = 0x7f0d0006;
    }
    public static final class string {
        public static final int cancel_button_label = 0x7f0e002a;
        public static final int choose_button_label = 0x7f0e0039;
        public static final int default_dir = 0x7f0e004a;
        public static final int error_dir_access = 0x7f0e0058;
        public static final int label_parent_dir = 0x7f0e0080;
        public static final int label_parent_directory = 0x7f0e0081;
        public static final int last_edit = 0x7f0e0082;
    }
    public static final class styleable {
        public static final int[] FilePickerPreference = { 0x7f0400a1, 0x7f0400ab, 0x7f040166, 0x7f040189, 0x7f040197, 0x7f040198, 0x7f0401eb };
        public static final int FilePickerPreference_error_dir = 0;
        public static final int FilePickerPreference_extensions = 1;
        public static final int FilePickerPreference_offset_dir = 2;
        public static final int FilePickerPreference_root_dir = 3;
        public static final int FilePickerPreference_selection_mode = 4;
        public static final int FilePickerPreference_selection_type = 5;
        public static final int FilePickerPreference_title_text = 6;
    }
}
